### ISSUE TITLE
result class nit

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#1]
https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/data/models/Response.kt#L3

this could be a sealed class
```

sealed class ClientResult<out T> {

  /**
   * Creates a new response object for a successful response
   * @param data the response data.
   */
  data class ClientSuccess<T>(val data: T) : ClientResult<T>()

  /**
   * Exception when the service response results in error
   * @param isServerError if the error was in the server
   * @param isNetworkError if the error is related to the network
   */
  data class ClientError(val isServerError: Boolean, val isNetworkError: Boolean) :
      ClientResult<Nothing>()
}
```

**Comment by Lucas-Israel** [comment]
solved with dagger hilt: https://github.com/Lucas-Israel/trybnb/commit/a55e10e66162b1baf426a0ae3f5baa42cad9e8da

**Comment by Lucas-Israel** [comment]
changed Result to ClientResult: https://github.com/Lucas-Israel/trybnb/commit/a2ad5d608ea8a868ebcbe452c66234736337e07e
