### ISSUE TITLE
use when instead of if

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#10]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/BookingViewModel.kt#L40-L50

 ```
val result = bookingRepository.getBookings()
when (result) {
    is ClientResult.ClientSuccess -> _bookings.postValue(result.data)
    is ClientResult.ClientError -> _fetchError.value = true
}

ApiIdlingResource.decrement()
```

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/bde7bedab8169670ca89fd0191ca0fb8cd2f83e7
