### ISSUE TITLE
Use BuildConfig

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#12]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/data/config/Configs.kt#L4

move this URL to the build config file
making use of the BuildConfig will make you project to look more professional and scalable

https://azevedorafaela.com/2015/09/17/environmental-variables-buildconfig-gradle-properties-and-android-studio/

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/32f2005693f72a858ed9ce76bfce2b5afe70f9bb
