### ISSUE TITLE
two model packages

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#13]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/data/api/model/Book.kt#L1

you have two models packages, you should have only one model package to make things more clear

create a "reponse" package for response classes

and a "model" package to models

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/08a14ed083a92a46102b75ba0388b2396bb0c6bf
