### ISSUE TITLE
util class in the model package

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#14]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/data/models/ClientResult.kt#L1

this is a Utility class, this should not be in a model package

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/08a14ed083a92a46102b75ba0388b2396bb0c6bf
