### ISSUE TITLE
useless variable can cause a memory leak

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#15]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/adapters/BookingAdapter.kt#L14

It’s not a good idea to keep this binding in a variable. The purpose of a RecyclerView is to destroy and recreate views, and keeping a reference to the binding will prevent the view from being recycled. Additionally, this variable is unnecessary

**Comment by Lucas-Israel** [comment]
@FilipeLipan like this? https://github.com/Lucas-Israel/trybnb/commit/f5141ad671d2ff132b699256e9872a05aed7fded

**Comment by FilipeLipan** [comment]
@Lucas-Israel  looks good
