### ISSUE TITLE
do not send View components to the viewmodel

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#17]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/ProfileViewModel.kt#L26

do not send View components to the viewmodel

use Strings, instead of "TextInputLayout "

**Comment by Lucas-Israel** [comment]
@FilipeLipan like this? https://github.com/Lucas-Israel/trybnb/commit/bd892d4f9dea5cb099eb9e48938b0a2084bc953d

refactor from the former code as it was not working as intended: https://github.com/Lucas-Israel/trybnb/commit/1f411f811f83228eafc1d5251b6a729eed5c79c9

**Comment by FilipeLipan** [comment]
nice ! this will work
