### ISSUE TITLE
it's a bad practice to use strings in Android

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#18]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/ProfileViewModel.kt#L49

it's a bad practice to use strings in Android

you should use string resouces
https://developer.android.com/guide/topics/resources/string-resource?hl=pt-br

you can use this solution
https://www.youtube.com/watch?v=mB1Lej0aDus

**Comment by Lucas-Israel** [comment]
@FilipeLipan how about this? https://github.com/Lucas-Israel/trybnb/commit/a8f7f5295074f30f7e9b6b204e54c9e1683c94a2

**Comment by FilipeLipan** [comment]
@Lucas-Israel  nice upgrade, you can use the `ProfileFragment` context instead of `container?.context`

to access strings you can use any context.

in this case you can use the Fragment context

**Comment by Lucas-Israel** [comment]
@FilipeLipan would it be better to use requireContext? https://github.com/Lucas-Israel/trybnb/commit/a49078903a2d69e6b4bc46e68eaba210e43ccfef
