### ISSUE TITLE
Move to an Util class

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#21]
move this function to a specific class, something like DataFormatterUtils

https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/views/fragments/CreateReservationFragment.kt#L100

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/134767995527ea33e1697fb83768080e1bc9e2ce
