### ISSUE TITLE
replace LiveData with MutableStateFlow 

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#22]
https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/ProfileViewModel.kt#L18

https://github.com/Lucas-Israel/trybnb/blob/8e504026dd19e408bed5cebadef48c296022eb45/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/BookingViewModel.kt#L26

replace with MutableStateFlow 

is not a good idea to use MutableLiveData and MutableStateFlow, both frameworks do the same thing, you can use both without any issue, but it does not look very professional

**Comment by Lucas-Israel** [comment]
solved: https://github.com/Lucas-Israel/trybnb/commit/d2f1e0517621b3799e14a7a64fb143c363f888d3
