### ISSUE TITLE
we should use dependency injection here

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#4]
https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/data/network/BookingDataSource.kt#L11

https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/data/repository/LoginRepository.kt#L8

https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/data/repository/BookingRepository.kt#L15

We can use dependency injection to initialize these classes. It's an advanced topic, probably the reason the course didn't cover it.

**Comment by Lucas-Israel** [comment]
solved with dagger hilt: https://github.com/Lucas-Israel/trybnb/commit/a55e10e66162b1baf426a0ae3f5baa42cad9e8da
