### ISSUE TITLE
observeForever adapter nit

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#6]
https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/ui/adapters/BookingAdapter.kt#L72

Never use observeForever; it's very bad practice and can lead to memory leaks.

Also, since you already have the booking list, you can use that list and remove the ViewModel property

**Comment by Lucas-Israel** [comment]
changed observeForever to observe: https://github.com/Lucas-Israel/trybnb/commit/f8554cca1669c08dfe41e1e6fac7444d1bb82679
