### ISSUE TITLE
data binding nit

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#7]
https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/res/layout/list_item_reservation.xml#L8

This works fine, but it is not well-regarded in the industry. We should avoid using data binding to set data and instead use a RecyclerView

https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView

you already have an Adapter it's a easy change

**Comment by Lucas-Israel** [comment]
like this? https://github.com/Lucas-Israel/trybnb/commit/d7ce754dfd15374a433a822298e52db1d7a9df1e

**Comment by FilipeLipan** [comment]
@Lucas-Israel yes, but avoid keeping this empty fields  -> android:text=""

also it's not a good practice to use "textview1" "textview2" "textview3" 
Try to use names that clearly explain the purpose of the field.

**Comment by Lucas-Israel** [comment]
solved here: https://github.com/Lucas-Israel/trybnb/commit/9be8644dc385e5ba8cd44c6b28617679e784c0de
