### ISSUE TITLE
viewmodel CoroutineScope(Dispatchers.IO) inside de the viewmodel

### ISSUE THREAD

**Issue by FilipeLipan** [Lucas-Israel/trybnb#8]
https://github.com/Lucas-Israel/trybnb/blob/b8ec8285ecb51c3396b7840be2fa4a55662e3f9d/app/src/main/java/com/betrybe/trybnb/ui/viewmodels/BookingViewModel.kt#L35

this and the others 
`CoroutineScope(Dispatchers.IO).launch {`
should be in the repository

inside the ViewModel you can use 
`
viewModelScope.launch {`
https://developer.android.com/topic/libraries/architecture/coroutines?hl=pt-br

also it's a bad practice to use `Dispatchers.IO` directly, it make the implementation impossible to test
you should use a wrapper singleton 

`
object DispatcherProvider {
       val IO: CoroutineContext = Dispatchers.IO
}
`

```
  override suspend fun getCall(): ClientResult<Object> {
    return withContext(dispatcherProvider.IO) {
}
}
```

**Comment by Lucas-Israel** [comment]
coroutines moved to repository: https://github.com/Lucas-Israel/trybnb/commit/a70edcb41d4773795bef776fcec44f27e2020d12
